#!/bin/sh
/web/cs2521/20T2/ass/ass2/hunt/dryrun/rungame.sh  Makefile dracula.c hunter.c DraculaView.c DraculaView.h HunterView.c HunterView.h GameView.c GameView.h Queue.c Queue.h testGameView.c testDraculaView.c testHunterView.c testMap.c testUtils.c testUtils.h > output.txt
