#!/bin/sh
rm output.txt
for x in {1..150}
do
/web/cs2521/20T2/ass/ass2/hunt/dryrun/rungame.sh  Makefile dracula.c hunter.c DraculaView.c DraculaView.h HunterView.c HunterView.h GameView.c GameView.h Queue.c Queue.h testGameView.c testDraculaView.c testHunterView.c testMap.c testUtils.c testUtils.h | tail -n -3 >> output.txt
done
